export enum ConnectorSettings {
    BACKEND_CONFIGURATION_FILE = 'BACKEND_CONFIGURATION_FILE',
    CONNECTOR_NAME = 'CONNECTOR_NAME',
    CONNECTOR_FILE = 'CONNECTOR_FILE',
    LOG_LEVEL = 'LOG_LEVEL'
}
